---
- hosts: redisserver
  become: yes
  tasks:
    - name: Update server
      apt: update_cache=yes
    - name: Add the Redis PPA
      apt_repository: repo='ppa:rwky/redis' update_cache=yes
    - name: Install Redis
      apt: name=redis-server state=installed
    - name: Start Redis server
      service: name=redis-server state=started

- hosts: proxyserver
  become: yes
  tasks:
    - name: Update server
      apt: update_cache=yes
    - name: Install nodejs
      apt: pkg=nodejs state=installed update_cache=true state=latest
    - name: Install npm
      apt: pkg=npm state=installed update_cache=true state=latest
    - name: Install git
      apt: pkg=git state=installed update_cache=true state=latest
    - name: Create symlink for nodejs
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    - name: "Install forever (to run load_balancer.js)."
      npm: name=forever global=yes state=present
    - name: "Check list of load_balancer.js apps running."
      command: forever list
      register: forever_list
      changed_when: false
    - name: Clone the git repo
      git: repo=https://github.com/ankitkumar93/WebApp.git dest=/root/WebApp
    - name: Intall dependencies
      npm: path=/root/WebApp
    - copy: src=../trigger/config.json dest=/root/WebApp/config.json mode="u=rwx,g=rx,o=rx"
    - name: "Start load_balancer.js app."
      command: /usr/local/bin/forever start /root/WebApp/load_balancer.js
      when: "forever_list.stdout.find('/root/WebApp/load_balancer.js') == -1"


- hosts: appserver
  become: yes
  tasks:
    - name: get latest packages
      action: apt update_cache=yes
    - name: Install jq
      apt: name=jq update_cache=true state=latest
    - name: Install npm
      apt: name=npm state=installed update_cache=true state=latest
    - name: Install nodejs
      apt: name=nodejs update_cache=true state=latest
    - name: Create symlink for nodejs
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    - name: Install git
      apt: name=git update_cache=true state=latest
    - name: install stress
      apt: pkg=stress state=installed
    - copy: src=../trigger/config.json dest=/root/config.json mode="u=rwx,g=rx,o=rx"
    - copy: src=./monitor/monitor.sh dest=/root/monitor.sh mode=0777
    - name: "Install forever (to run server.js app)."
      npm: name=forever global=yes state=present
    - name: Clone the git repo
      git: repo=https://github.com/ankitkumar93/WebApp.git dest=/root/WebApp
    - name: Intall dependencies
      npm: path=/root/WebApp
    - name: "Check list of server.js apps running."
      command: forever list
      register: forever_list
      changed_when: false
    - name : "Copy config.json to WebApp"
      command: cp /root/config.json /root/WebApp/config.json