---
- hosts: appserver
  become: yes
  tasks:
    - name: Clone the git repo
      git: repo=https://github.com/ankitkumar93/WebApp.git dest=/home/ubuntu/WebApp
    - name: Intall dependencies
      npm: path=/home/ubuntu/WebApp
    - name: "Check list of server.js apps running."
      command: forever list
      register: forever_list
      changed_when: false
    - name: "Start server.js app."
      command: sudo forever start /home/ubuntu/WebApp/server.js
      when: "forever_list.stdout.find('/home/ubuntu/WebApp/server.js') == -1"
    - name : Move config.json to WebApp
      command: mv /home/ubuntu/config.json /home/ubuntu/WebApp/config.json
